openapi: "3.0.3"
info:
  title: "Musiquinhas"
  version: "1.0.0"
  description: "API para musicas"
servers:
  - url: "https://api.musiquinhas.com/v1"
    description: "Produção"
paths:
  /musica:
    get:
      summary: "Listar musicas"
      operationId: "listTests"
      tags: ["musicas"]
      responses:
        "200":
          description: "Lista de Musicas"
    post:
      summary: "Criar Musica"
      operationId: "createMusica"
      tags: ["musicas"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NovaMusica"
      responses:
        "201":
          description: "Musica criada"
        "400":
          description: "Dados inválidos"
  /Musica/{id}:
    get:
      summary: "Buscar musica"
      operationId: "getMusica"
      tags: ["musicas"]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Encontrado"
        "404":
          description: "Não encontrado"
components:
  schemas:
    NovaMusica:
      type: object
      required: [titulo]
      properties:
        titulo:
          type: string
          example: "Minha musiquinhas"